name = "zerochat"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "./public"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom", "RateLimiter"]

[[kv_namespaces]]
binding = "THREAD_MAP"
id = "4daf01ff6e5a4542ac6f106d67461f15"

[ai]
binding = "AI"

[vars]
TELEGRAM_CHAT_ID = "-1003941424940"
